#  __  __      ____       ____                           __
# /\ \/\ \    /\  _`\    /\  _`\                        /\ \
# \ \ `\\ \   \ \ \L\ \  \ \ \L\ \      __       ___    \ \ \/'\
#  \ \ , ` \   \ \  _ <'  \ \ ,  /    /'__`\   /' _ `\   \ \ , <
#   \ \ \`\ \   \ \ \L\ \  \ \ \\ \  /\ \L\.\_ /\ \/\ \   \ \ \\`\
#    \ \_\ \_\   \ \____/   \ \_\ \_\\ \__/.\_\\ \_\ \_\   \ \_\ \_\
#     \/_/\/_/    \/___/     \/_/\/ / \/__/\/_/ \/_/\/_/    \/_/\/_/
#
# NineVocalRank
# Github:https://github.com/NineBiliTeam/NineBiliRank
# Powered By FastAPI & Httpx
#
# 在这里修改你的NineBiliRank服务端的模块配置
# 如果其他模块有配置要求，请修改
# 关于YAML标准，请查阅https://www.runoob.com/w3cnote/yaml-intro.html4
#
example:
  a: 1
  b: 2
  c:
    - 1
    - 2
  d:
    e: 1
    f: 2
reg_from_file:
  # 这是内置钩子：从文件批量导入
  # 的配置文件
  # txt文件位置
  path: "./test.txt"
