"""empty message

Revision ID: 6f15cc66befc
Revises:
Create Date: 2025-02-06 18:22:20.709404

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6f15cc66befc"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Video",
        sa.Column("view", sa.Integer(), nullable=False),
        sa.Column("like", sa.Integer(), nullable=False),
        sa.Column("coin", sa.Integer(), nullable=False),
        sa.Column("favorite", sa.Integer(), nullable=False),
        sa.Column("reply", sa.Integer(), nullable=False),
        sa.Column("share", sa.Integer(), nullable=False),
        sa.Column("danmaku", sa.Integer(), nullable=False),
        sa.Column("uploader_mid", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("avid", sa.String(length=64), nullable=False),
        sa.Column("bvid", sa.String(length=64), nullable=False),
        sa.Column("tid", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.Column("pic", sa.String(length=256), nullable=False),
        sa.Column("pages", sa.Integer(), nullable=False),
        sa.Column("nbid", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("nbid"),
    )
    op.create_table(
        "fresh_achievement_video",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("view", sa.Integer(), nullable=False),
        sa.Column("bvid", sa.String(length=32), nullable=False),
        sa.Column("timestamp", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "monitored_video",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("view", sa.Integer(), nullable=False),
        sa.Column("bvid", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "uploader",
        sa.Column("mid", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("fans", sa.Integer(), nullable=False),
        sa.Column("archive_count", sa.Integer(), nullable=False),
        sa.Column("nbuid", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("nbuid"),
    )
    op.create_table(
        "video_sorted_by_increase_view",
        sa.Column("rank", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("view", sa.Integer(), nullable=False),
        sa.Column("bvid", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("rank"),
    )
    op.create_table(
        "video_sorted_by_vrank_score",
        sa.Column("rank", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("bvid", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("rank"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("video_sorted_by_vrank_score")
    op.drop_table("video_sorted_by_increase_view")
    op.drop_table("uploader")
    op.drop_table("monitored_video")
    op.drop_table("fresh_achievement_video")
    op.drop_table("Video")
    # ### end Alembic commands ###
